-
  branches:
      only:
        - master
  version: 1.0.{build}
  image: Visual Studio 2017
  environment:
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: Fa1CPP5b0AEtKdI1cPJOwFalpn/bKgcbBYw6KFdSN7S2YIn9hQsNcgDEmc5EnPhD
  build_script:
  - ps: .\build.ps1 -verbosity Diagnostic
  test: off
-
  branches:
      only:
        - develop
  version: 1.0.{build}
  image: Visual Studio 2017
  environment:
    NUGET_SOURCE: https://www.myget.org/F/xabluhq/api/v2/package
    NUGET_APIKEY:
      secure: tyxmEfZy6Pn3y6WrIGSElHFII1LpMaArT2Sv+zTEcIp1/l8Y2L2rHO+XoG2vXUDg
  build_script:
  - ps: .\build.ps1 -verbosity Diagnostic
  test: off
